[project]
name = "videourl-to-audio"
version = "0.1.0"
description = "Download video from URL and extract audio"
requires-python = ">=3.8"
dependencies = [
    "typer>=0.12.0",
    "yt-dlp>=2024.0.0",
]

[project.scripts]
videourl-to-audio = "main:app"

